Post component
nerraou/ft_transcendence pull request #47
Opened 2023-10-23 13:52 UTC by zridi-mahmoud

2023-10-23 14:43 UTC, nerraou requested changes
Post belongs to Molecules .kindly move it from Atoms

2023-10-23 14:43 UTC, nerraou commented on frontend/src/components/atoms/feed/Post.tsx
> +const UserCard = ({ user }: { user: User }) => {
Avoid inline type

2023-10-23 14:43 UTC, nerraou commented on frontend/src/components/atoms/feed/Post.tsx
> +  const formatCount = (count: number) => {
Avoid shadowing; check Eslent, preferably get it out of the component

2023-10-23 14:43 UTC, nerraou commented on frontend/src/components/atoms/icons/outline/Like.tsx
> +        stroke-linejoin="round"
Make the SVG props JSX compatible

2023-10-28 12:17 UTC, oxidia requested changes

2023-10-28 12:17 UTC, oxidia commented on frontend/src/components/atoms/feed/Post.tsx
> +const UserCard = ({ user }: { user: User }) => {
Create
```ts
interface UserCardProps {
  user: User;
}

2023-10-28 12:17 UTC, oxidia commented on frontend/src/components/atoms/feed/Post.tsx
> +interface LikeProps {
rename to LikeSectionProps

2023-11-06 12:12 UTC, oxidia approved these changes

2023-11-06 12:16 UTC, oxidia approved these changes

2023-11-06 12:21 UTC, nerraou approved these changes
LGTM

2023-11-06 12:21 UTC, merged